const cds = require('@sap/cds');

cds.on('bootstrap', (app) => {
    if (process.env.NODE_ENV === 'production') {
        const passport = require('passport');
        const { XssecPassportStrategy, XsuaaService } = require('@sap/xssec');
        const xsenv = require('@sap/xsenv');
        try {
            const services = xsenv.getServices({ uaa: { tag: 'xsuaa' } });
            passport.use('JWT', new XssecPassportStrategy(new XsuaaService(services.uaa)));
            app.use('/api', passport.initialize());
            app.use('/api', passport.authenticate('JWT', { session: false }));
        } catch (error) {
            console.error('[auth] Error setting up XSUAA JWT Strategy:', error);
        }
    }

    // Return user info and handle CSRF token fetch from approuter
    app.get('/api/me', (req, res) => {
        // req.user is populated by basic authentication for local dev
        // req.authInfo is populated by xssec for production Approuter
        const user = req.user || req.authInfo;

        if (user) {
            // Local dev (mock strategy) uses a different object structure than XSUAA's authInfo
            const logonName = user.id || (user.getLogonName && user.getLogonName()) || 'mock-user';
            const email = (user.getEmail && user.getEmail()) || 'mock@example.com';
            const firstName = (user.getGivenName && user.getGivenName()) || 'Mock';
            const lastName = (user.getFamilyName && user.getFamilyName()) || 'User';

            res.json({
                userId: logonName,
                email: email,
                firstName: firstName,
                lastName: lastName
            });
        } else if (process.env.NODE_ENV !== 'production') {
            // Local dev fallback when accessed directly without cds mock auth wrapper
            res.json({
                userId: 'dev-user',
                email: 'dev@local.host',
                firstName: 'Local',
                lastName: 'Developer'
            });
        } else {
            console.warn("No user context found in request.");
            res.status(401).json({ error: "Not authenticated" });
        }
    });

    app.post('/api/fetch-bom', async (req, res) => {
        try {
            const destinationName = req.body.destinationName;
            if (!destinationName) {
                return res.status(400).json({ error: "Missing destinationName" });
            }

            // === LOCAL DEVELOPMENT MOCK ===
            if (process.env.NODE_ENV !== 'production') {
                console.log(`[local-mock] Pretending to fetch OData from Destination: ${destinationName}`);
                return res.json({
                    success: true,
                    data: [
                        { BillOfMaterialItemCategory: "L", Language: "EN", BillOfMaterialItemCategoryDesc: "Stock item (Mock)" },
                        { BillOfMaterialItemCategory: "N", Language: "EN", BillOfMaterialItemCategoryDesc: "Non-stock item (Mock)" },
                        { BillOfMaterialItemCategory: "T", Language: "EN", BillOfMaterialItemCategoryDesc: "Text item (Mock)" }
                    ]
                });
            }

            // === PRODUCTION (SAP BTP) EXECUTION ===
            // The external service name generated by `cds import`
            const metadataService = 'API_BILL_OF_MATERIAL_SRV';

            // Connects dynamically to the given destination on BTP
            const bomService = await cds.connect.to(metadataService, {
                credentials: { destination: destinationName }
            });

            // Principal Propagation: Bind the current user's HTTP Request context into the CAP transaction
            const tx = bomService.tx(req);

            // Execute Native CAP SELECT against the imported OData Entity
            const BOM_ENTITY = 'API_BILL_OF_MATERIAL_SRV.A_BOMItemCategoryText';
            const data = await tx.run(SELECT.from(BOM_ENTITY).limit(50));

            res.json({ success: true, data: data });
        } catch (error) {
            console.error('[bom-fetch] Error calling OData On-Premise:', error.message);
            res.status(500).json({ error: error.message, details: error.response?.data || error.stack });
        }
    });
});

module.exports = cds.server;
